---
- name: Installs necessary packages
  hosts: linux
  become: yes

  tasks:
   - name: Upgrade all packages
     yum:
       name: '*'
       state: latest
   - name: Installation
     yum: pkg={{ item }} state=latest
     with_items:
       - mariadb-server
       - mariadb
       - php
       - git
       - htop
       - net-tools
       - tree
   - name: Start web server and start it on boot centos
     service: name=httpd state=started enabled=yes  
   - name: Start mariadb server and start it on boot centos  
     service: name=mariadb state=started enabled=yes
